namespace CommitApi.Models.Graph;

/// <summary>
/// A single replan option generated by ReplanGenerator for a given cascade.
/// </summary>
/// <param name="OptionId">"A" | "B" | "C"</param>
/// <param name="Label">Short option name shown in Adaptive Card.</param>
/// <param name="Description">Explanation of this replan strategy.</param>
/// <param name="Confidence">0–1, how confident the engine is this will work.</param>
/// <param name="RequiredActions">Ordered list of actions required to execute this option.</param>
public record ReplanOption(
    string OptionId,
    string Label,
    string Description,
    double Confidence,
    IReadOnlyList<string> RequiredActions);
